version: '3'
services:
   web:
      build:
        context: ./config/php
        dockerfile: Dockerfile
      container_name: web
      restart: always
      user: application
      environment:
        - WEB_ALIAS_DOMAIN=magexto.local
        - WEB_DOCUMENT_ROOT=/app/htdocs/pub
        - PHP_DATE_TIMEZONE=EST
        - PHP_DISPLAY_ERRORS=1
        - PHP_MEMORY_LIMIT=2048M
        - PHP_MAX_EXECUTION_TIME=600
        - PHP_POST_MAX_SIZE=500M
        - PHP_UPLOAD_MAX_FILESIZE=1024M
      volumes:
        - ./magento:/app:cached
        - ./config/php:/usr/local/etc/php
      ports:
        - "80:80"
        - "443:443"
        - "32823:22"
      links:
        - mysql
      networks:
        - mynet

   elasticsearch:
      image: elasticsearch:7.17.8
      container_name: elasticsearch
      networks:
        - mynet
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        discovery.type: single-node

   mysql:
       image: mysql:8.0.31
       container_name: mysql
       restart: always
       networks:
        - mynet
       ports:
         - "3306:3306"
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=magento
       volumes:
         - dbdata:/var/lib/mysql

   phpmyadmin:
       container_name: phpmyadmin
       restart: always
       networks:
         - mynet
       image: phpmyadmin/phpmyadmin:latest
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - PMA_USER=root
         - PMA_PASSWORD=root
       ports:
         - "8080:80"
       links:
         - mysql:db
       depends_on:
         - mysql
networks:
    mynet:
        driver: bridge

volumes:
   dbdata:
       external: false